language: node_js

node_js:
  - "8"

addons:
  apt:
    sources:
      - trusty-media
    packages:
      - ffmpeg
      - libasound2-dev

cache: yarn

script:
  - yarn config set mpg123-backend dummy
  - yarn install
  - yarn run lint:all
  - yarn run test:all
  - yarn run e2e -- -e chrome-headless