language: node_js

node_js:
  - "8"

addons:
  apt:
    sources:
      - trusty-media
    packages:
      - ffmpeg
      - libasound2-dev

script:
  - npm install -mpg123-backend=dummy
  - npm run lint:all
  - npm run test:all
  - npm run e2e -- -e chrome-headless